### ISSUE TITLE
how can check is the user login

### ISSUE THREAD

**Issue by techpoints** [harsh159357/flutter_client_php_backend#1]
hello,
how can check is the user login In any pages ..
Meaning ... Any page I want to check user what do you do?
exp: in flutter drawer, if user login ok Show some links
in php like :
```
  if(userIsSignedIn  == true){
      return ....
  }else{
      return ....
  }
```

**Comment by harsh159357** [comment]
@techpoints 
I am using Shared Preference to check whether the user is logged in the app or not.

Check out for the following things in this project -

1. Code for Storage and Retrieval for checking whether the user is logged in or not -
    a) Check the following file **app_shared_preferences.dart** from **line 38 to 49**

2. **splash_page.dart**  Line  no 73 using isUserLoggedIn() from app_shared_preferences.dart

3.  Also, I am storing value for User Logged in inside login_page.dart line no 202

Still, you have any doubt let me know.

**Comment by techpoints** [comment]
Thank you
Is this code correct?

I got it wrong:
I/flutter (17354): Another exception was thrown: type 'Future<dynamic>' is not a subtype of type 'Widget'
https://image.ibb.co/koJ66L/5435435.jpg

```
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:kadiksa/utils/app_shared_preferences.dart';

class CheckIsLoginPage extends StatefulWidget {
  @override
  createState() => new CheckIsLogin();
}

class CheckIsLogin extends State<CheckIsLoginPage> {
  @override
  Widget build(BuildContext context) {
    return _handleTapEvent();
  }

  _handleTapEvent() async {
    bool isLoggedIn = await AppSharedPreferences.isUserLoggedIn();
    if (this.mounted) {
      setState(() {
        if (isLoggedIn != null && isLoggedIn) {
          return Drawer(
            child: ListView(
              scrollDirection: Axis.vertical,
              children: <Widget>[
                ListTile(
                  title: Text('Home'),
                ),
                ListTile(
                  title: Text('Login'),
                ),
              ],
            ),
          );
        } else {
          return Drawer(
            child: ListView(
              scrollDirection: Axis.vertical,
              children: <Widget>[
                ListTile(
                  title: Text('Home'),
                ),
                ListTile(
                  title: Text('LogOut'),
                ),
              ],
            ),
          );
        }
      });
    }
  }
}
```

**Comment by harsh159357** [comment]
@techpoints the problem is that _handleTapEvent() method is not having the return type of widget. Your method return type is async. So you are getting the error - I/flutter (17354): Another exception was thrown: type 'Future' is not a subtype of type 'Widget'
