### ISSUE TITLE
What flutter version?

### ISSUE THREAD

**Issue by rexdarel** [harsh159357/flutter_client_php_backend#2]
Hi, I've got errors regarding on the packages you used. Is this updated to the current version of flutter?

**Comment by rexdarel** [comment]
I manage to build this one. but got some problem connecting to the backend. How can I use this using SLIM PHP framework as API?

**Comment by harsh159357** [comment]
@rexdarel just use the PHP code what I have provided inside the [PhpBackend](https://github.com/harsh159357/flutter_client_php_backend/tree/master/phpbackend) folder and the [Sql](https://github.com/harsh159357/flutter_client_php_backend/blob/master/phpbackend/FlutterClientPhpBackend.sql) files for your table structure in database. This app is just a sample to show the usage of PHP and Flutter together. 

I don't know PHP Slim framework so. Just give this project a try using free hosting 000webhost or any other.
