### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by muriminyaga** [harsh159357/flutter_client_php_backend#3]
Because every version of flutter_test from sdk depends on http 0.11.3+17 and flutter_client_php_backend depends on http ^0.12.0, flutter_test from sdk is forbidden.
So, because flutter_client_php_backend depends on flutter_test any from sdk, version solving failed.

pub get failed (1)

**Comment by harsh159357** [comment]
@muriminyaga hey buddy is your issue resolved or are you still facing it. Cuz I am not facing it on my side.

**Comment by muriminyaga** [comment]
> @muriminyaga hey buddy is your issue resolved or are you still facing it. Cuz I am not facing it on my side.

I sorted it by upgrading the flutter plugin.Thanks

**Comment by harsh159357** [comment]
@muriminyaga Nice to hear this good news. Keep Fluttering.
