### ISSUE TITLE
REST API METHOD POST

### ISSUE THREAD

**Issue by babycorp** [harsh159357/flutter_client_php_backend#5]
Could you give some tutorial with picture to try postman in your api ? sorry I'm newbie in flutter and postman...

**Comment by harsh159357** [comment]
@babycorp Thanks for reaching out you just need to import the following collection in the  Postman using the following link - https://www.getpostman.com/collections/80394d2fc7c2aed05cc5

Download the Postman from Here - https://www.getpostman.com/

For tutorials, you can follow this link. (https://www.youtube.com/watch?v=juldrxDrSH0&list=PLhW3qG5bs-L-oT0GenwPLcJAPD_SiFK3C)

Hope these things will help you out.

Feel free to ask any question if still there is any doubt left.
