### ISSUE TITLE
Error 502

### ISSUE THREAD

**Issue by JKDesignslk** [harsh159357/flutter_client_php_backend#7]
App is registering at your url. But when I change it to mine I'm getting 502 error. Why, http://movie.jkdesigns.lk

1. Created database
2. Imported SQL file
3. Changed the DBOperations.php credentials....

Issue Found:

php versions -> PDO not enabled - fixed
php versions -> json not enabled - fixed
renamed functions.php into  Functions.php as in index.php line #3 require_once 'Functions.php';

**Comment by harsh159357** [comment]
@JKDesignslk  is your issue resolved or is it still there ?
