### ISSUE TITLE
Help adding new fields

### ISSUE THREAD

**Issue by gugoan** [harsh159357/flutter_client_php_backend#8]
Your project ran right, very good to start the studies. Could you help me add new fields in the registration form? It already includes 3 fields in the database (type VARCHAR) and I also include tbm in the flutter code, but I believe I didn't do it right. "No Internet Connection" Appears

Where do I really need to change?

**Comment by harsh159357** [comment]
@gugoan are you able to add new fields or you are still stuck.

If yes we can connect remotely over anydesk

**Comment by harsh159357** [comment]
@gugoan If issue is not resolved reopen it.
